Repository nvisionative/nvQuickTheme, pull requests merged in 2022-10, with the labels that each got.

#304 Update division signs
  src/scss/mixins/_mixins.scss
  src/scss/variables/_bs-overrides.scss
Labels: enhancement

#307 Fixes calc usage in mixins.
  src/scss/mixins/_mixins.scss
Labels: bug, hacktoberfest

#306 Replace gulp notify
  gulpfile.js
  package.json
  yarn.lock
Labels: enhancement, hacktoberfest

#311 Update to Bootstrap 5
  package.json
  partials/_header.ascx
  src/scss/variables/_bs-overrides.scss
  yarn.lock
Labels: enhancement, hacktoberfest

#314 Remove divider borders from desktop submenu items
  src/scss/components/_nav.scss
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#315 Implement GitHub actions for build
  .github/workflows/build.yml
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
