Repository nvisionative/nvQuickTheme, pull requests merged in 2022-11, with the labels that each got.

#318 Remove `gren` release management solution
  .grenrc.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#320 Cleanup README file to add badges reflecting current tooling
  README.md
Labels: bug, hacktoberfest

#321 Update gulpfile.js to follow ES2015+ best practices
  gulpfile.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#323 Address all sonarcloud bugs
  docs/_layouts/default.html
  src/scss/components/_dnn.scss
Labels: bug, hacktoberfest

#325 Resolve all `sonarcloud` code smells
  src/js/customMenu.js
  src/scss/components/_dnn.scss
  src/scss/components/_nav.scss
Labels: bug, hacktoberfest, hacktoberfest-accepted

#326 Resolve bug with duplicate style in `_dnn.scss`
  src/scss/components/_dnn.scss
Labels: bug, hacktoberfest, hacktoberfest-accepted

#327 Resolve bug with duplicate style in _dnn.scss
  src/scss/components/_dnn.scss
Labels: bug, hacktoberfest

#329 Refactor desktop RazorMenu to remove duplicate code
  menus/desktop/RazorMenu.cshtml
  package.json
  src/js/customMenu.js
Labels: bug, hacktoberfest

#331 Move backlink to razor
  menus/mobile/RazorMenu.cshtml
  src/js/customMenu.js
Labels: bug, enhancement

#332 Added italic counterparts of theme fonts
  partials/_includes.ascx
  src/fonts/OpenSans-BoldItalic.woff
  src/fonts/OpenSans-BoldItalic.woff2
  src/fonts/OpenSans-ExtraBoldItalic.woff
  src/fonts/OpenSans-ExtraBoldItalic.woff2
  src/fonts/OpenSans-Italic.woff
  src/fonts/OpenSans-Italic.woff2
  src/fonts/OpenSans-LightItalic.woff
  src/fonts/OpenSans-LightItalic.woff2
  src/fonts/OpenSans-SemiBoldItalic.woff
  src/fonts/OpenSans-SemiBoldItalic.woff2
  src/scss/variables/_fonts.scss
Labels: enhancement

#334 Update dependencies
  package.json
  yarn.lock
Labels: maintenance

#337 Merge `develop` into `main` for `3.0.0` release
  .github/workflows/build.yml
  .grenrc.js
  README.md
  docs/_layouts/default.html
  gulpfile.js
  menus/desktop/RazorMenu.cshtml
  menus/desktop/menudef.xml
  menus/main/MainMenu.txt
  menus/mobile/RazorMenu.cshtml
  menus/mobile/menudef.xml
  menus/razor/RazorMenu.cshtml
  package.json
  partials/_header.ascx
  partials/_includes.ascx
  src/assets/jquery.slimmenu.min.js
  src/fonts/OpenSans-BoldItalic.woff
  src/fonts/OpenSans-BoldItalic.woff2
  src/fonts/OpenSans-ExtraBoldItalic.woff
  src/fonts/OpenSans-ExtraBoldItalic.woff2
  src/fonts/OpenSans-Italic.woff
  src/fonts/OpenSans-Italic.woff2
  src/fonts/OpenSans-LightItalic.woff
  src/fonts/OpenSans-LightItalic.woff2
  src/fonts/OpenSans-SemiBoldItalic.woff
  src/fonts/OpenSans-SemiBoldItalic.woff2
  src/js/custom.js
  src/js/customMenu.js
  src/scss/components/_dnn.scss
  src/scss/components/_nav.scss
  src/scss/mixins/_mixins.scss
  src/scss/variables/_bs-overrides.scss
  src/scss/variables/_fonts.scss
  yarn.lock
Labels: maintenance

#338 Increment project details version for 3.0.0 release
  manifest.dnn
  project-details.json
Labels: maintenance

#339 Merge `develop` into `main` for `3.0.0` release
  manifest.dnn
  project-details.json
Labels: maintenance

#340 Name change of the package command in V3.0
  docs/Commands.md
Labels: documentation
