Repository nvisionative/nvQuickTheme, pull requests merged in 2023-12, with the labels that each got.

#358 Update font awesome to latest version and usage
  gulpfile.js
  package.json
  partials/_includes.ascx
  yarn.lock
Labels: enhancement

#360 Upgrade `browser-sync` and resolve `PersonaBar` issue
  gulpfile.js
  package.json
  yarn.lock
Labels: bug

#361 Remove support for `eot`, `otf`, `woff`, and update mime type for `woff2`
  manifest.dnn
  partials/_includes.ascx
  src/fonts/OpenSans-Bold.woff
  src/fonts/OpenSans-BoldItalic.woff
  src/fonts/OpenSans-ExtraBold.woff
  src/fonts/OpenSans-ExtraBoldItalic.woff
  src/fonts/OpenSans-Italic.woff
  src/fonts/OpenSans-Light.woff
  src/fonts/OpenSans-LightItalic.woff
  src/fonts/OpenSans-Regular.woff
  src/fonts/OpenSans-SemiBold.woff
  src/fonts/OpenSans-SemiBoldItalic.woff
Labels: enhancement

#362 Merge `develop` into `main` for `3.1.0` release
  docs/Commands.md
  gulpfile.js
  manifest.dnn
  package.json
  partials/_includes.ascx
  src/fonts/OpenSans-Bold.woff
  src/fonts/OpenSans-BoldItalic.woff
  src/fonts/OpenSans-ExtraBold.woff
  src/fonts/OpenSans-ExtraBoldItalic.woff
  src/fonts/OpenSans-Italic.woff
  src/fonts/OpenSans-Light.woff
  src/fonts/OpenSans-LightItalic.woff
  src/fonts/OpenSans-Regular.woff
  src/fonts/OpenSans-SemiBold.woff
  src/fonts/OpenSans-SemiBoldItalic.woff
  src/scss/components/_dnn.scss
  yarn.lock
Labels: maintenance

#363 Increment version for 3.1.0 release
  manifest.dnn
  package.json
  project-details.json
Labels: maintenance

#364 Merge `develop` into `main` for `3.1.0` release
  manifest.dnn
  package.json
  project-details.json
Labels: maintenance
